### ISSUE TITLE
Library used for Kriging interpolation in Appendix 9

### ISSUE THREAD

**Issue by akherlan** [mgimond/Spatial_pre2021#5]
Dear, Mr. Gimond. What is library package for `variogram()` in A9? `Variogram()` with capital V in `spatstat` and `variogram()` in `gstat` couldn't give my trial succeed. I tried to follow the instruction Kriging interpolation in Appendix 9.
My apologies to this question, I couldn't get your contact except on Github account.
Thanks.

**Comment by mgimond** [comment]
Hi Andi,

The variogram function I use in the appendix is pulled from the gstat package (the lowercase "v" function). What error were you getting? 

Here's a reprex that works on my end  on a Windows 10 box (R version 3.6.0, gstat_2.0-2, rgdal_1.4-3 sp_1.3-:

```
library(rgdal)
library(gstat)

# Load precipitation data
z <- gzcon(url("http://colby.edu/~mgimond/Spatial/Data/precip.rds"))
P <- readRDS(z)

# Load Texas boudary map
z <- gzcon(url("http://colby.edu/~mgimond/Spatial/Data/texas.rds"))
W <- readRDS(z)

# Replace point boundary extent with that of Texas
P@bbox <- W@bbox

# Add X and Y to P
P$X <- coordinates(P)[,1]
P$Y <- coordinates(P)[,2]

# Create variogram model using gstat::variagram()
f.1 <- as.formula(Precip_in ~ X + Y) 
var.smpl <- variogram(f.1, P, cloud = FALSE, cutoff=1000000, width=89900)

dat.fit  <- fit.variogram(var.smpl, fit.ranges = FALSE, fit.sills = FALSE,
                          vgm(psill=14, model="Sph", range=590000, nugget=0))

# The following plot allows us to assess the fit
plot(var.smpl, dat.fit, xlim=c(0,1000000))
```

**Comment by akherlan** [comment]
Thank you!
Coordinates (X,Y) was not include in `P`'s data.frame yet.
So, when I run this: `var.smpl <- variogram(f.1, P, cloud = FALSE, cutoff=1000000, width=89900)`
I've got an error like this: `rror in eval(predvars, data, env) : object 'X' not found`
The formula `f.1` did not found the `X` in `P`'s data.

**Comment by mgimond** [comment]
I'm glad that you got it to work. Cheers!
