### ISSUE TITLE
Conflicting interpretation of K function on Chapter 11

### ISSUE THREAD

**Issue by dhersz** [mgimond/Spatial_pre2021#7]
Reading [chapter 11](https://mgimond.github.io/Spatial/point-pattern-analysis.html) I noticed two conflicting interpretations of the value of K function vs K expectation.

In section 11.3.2.1, after figure 11.17:

`K values greater than Kexpected indicate clustering of points at a given distance band; K values less than Kexpected indicate dispersion of points at a given distance band. In our example, the stores appear to be more clustered than expected at distances greater than 12 km.`

In section 11.3.2.2, in figure 11.18 legend:

`Figure 11.18: L-function (a simple transformation of the K-function). This graph makes it easier to compare K with Kexpected at lower distance values. It appears that Walmart locations are more clustered than expected under CSR/IRP up to a distance of 12 km but more dispersed at distances greater than 12 km. `

Best regards.

**Comment by mgimond** [comment]
Thanks for catching the inconsistency in my statement. This issue was raised in a [PR](https://github.com/mgimond/Spatial/pull/6). Working on it now. Should be pushed to master sometime this week.
Cheers!

**Comment by dhersz** [comment]
Oops, I'm sorry, I checked to see if any issue had been raised on this point but I failed to check the pull requests. Thanks for the great material anyway!
